import { Layout } from "@/components";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Layout.Header>
          <div className="header__root__title">
            <h1 className="header__root__title--root">
              <span>WEB DEVELOPER</span>
              <span>DESKTOP DEVELOPER</span>
              <span>SISTEM DESIGN ENTUSIAST</span>
            </h1>
          </div>
        </Layout.Header>
        <Layout.Content>
          <p>hola</p>
        </Layout.Content>
        <Layout.Footer>
          <p>footer</p>
        </Layout.Footer>
      </Layout>
    </div>
  );
}
